# Site settings
title: Louis Theran
email: louis.theran@aalto.fi
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theran.lt" # the base hostname & protocol for your site
github_username:  theran
#twitter_username: louistheran

# exclude from generating co-authors
my_authortag: louis

# current seminar term
seminar_current_term: spring2016

# collections
collections:
    papers:
        output: true
    seminartalks:
        output: true

# Build settings
markdown: kramdown
future: true