# Site settings
title: Your Name
email: your.email@your.domain
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yoursite" # the base hostname & protocol for your site
github_username:  githubaccount
twitter_username: twitteraccount

# exclude from generating co-authors
my_authortag: louis

# collections
collections:
    papers:
        output: true

# Build settings
markdown: kramdown
